apiVersion: apps/v1
kind: Deployment
metadata:
  name: infer  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infer
  template:
    metadata:
      labels:
        app: infer
    spec:
      imagePullSecrets:
        - name: harbor-registry
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: models-data
      containers:
      - name: infer
        image: harbor.shared.acrist-services.com/dsy/ml/train:1.0.8
        volumeMounts:
        - name: data
          mountPath: /usr/local/models
        args: ["main.py"]
        ports:
        - name: http
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: infer  
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
  selector:
    app: infer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infer
spec:
  ingressClassName: nginx
  rules:
  - host: infer.dev.acrist-services.com
    http:
      paths:
      - backend:
          service:
            name: infer
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - infer.dev.acrist-services.com
    secretName: dev-tls-secret
