apiVersion: batch/v1
kind: Job
metadata:
  name: modeltrain
  labels:
    app: modeltrain
    project: ml
spec:
  template:
    spec:
      nodeSelector:
        type: processing
      imagePullSecrets:
        - name: harbor-registry
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: models-data
      containers:
      - name: train
        image: harbor.shared.acrist-services.com/dsy/ml/train:1.0.7
        volumeMounts:
        - name: data
          mountPath: /usr/local/models
      restartPolicy: Never
  backoffLimit: 1
