name: empty-django-app
services:
  - name: web
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    routes:
      - path: /
    github:
      repo: "iwootten/empty-django-app"
      branch: master
      deploy_on_push: true
    build_command: ""
    run_command: "python manage.py migrate; gunicorn --worker-tmp-dir /dev/shm djempty.wsgi"
    envs:
    - key: APP_DOMAIN
      scope: RUN_TIME
      value: ${APP_DOMAIN}
region: ams3