packages:
  - name: ynov
    functions:
      - name: hello
        binary: false
        runtime: 'nodejs:default'
        web: true
      - name: hello_sacha
        binary: false
        runtime: 'nodejs:default'
        web: true
