environment:
  QUERY: 'filetype:xlsx budget 2024'
packages:
  - name: ynov
    functions:
      - name: dorking
        binary: false
        runtime: 'python:default'
        web: true
        
