environment:
  QUERY: 'site:example.com inurl:admin'
packages:
  - name: ynov
    functions:
      - name: dorking
        binary: false
        runtime: 'python:default'
        web: true
        limits:
          memory: 1024
        
