# environment:
#   QUERY: 'filetype:xlsx budget 2024'
packages:
  - name: ynov
    functions:
      - name: kraken
        binary: false
        runtime: 'python:default'
        web: true
        
