#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

groups:
    - docker

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - unattended-upgrades
  - make 
  - build-essential 
  - libssl-dev 
  - zlib1g-dev 
  - libbz2-dev 
  - libreadline-dev 
  - libsqlite3-dev 
  - curl 
  - git 
  - libncursesw5-dev 
  - xz-utils 
  - tk-dev 
  - libxml2-dev 
  - libxmlsec1-dev 
  - libffi-dev 
  - liblzma-dev
  - postgresql-client

runcmd:
  - curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg
  - sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'
  - apt install pgadmin4 -y
  - apt install pgadmin4-web -y

